### ISSUE TITLE
代码可能存在书写不规范导致Python运行报错

### ISSUE THREAD

**Issue by 2020sudo** [lxmusics/lx-music-api-server#2]
**运行报错**
```shell
"E:\lx-music-api-server\python\main.py", line 21, in <module>
    from common import config
  File "E:\lx-music-api-server\python\common\config.py", line 56    
    "key": {
           ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?”
```

- 根据报错信息，问题似乎出现在 "config.py" 文件的第 56 行，提示缺少逗号。这个错误通常发生在字典或列表中的最后一个元素后面缺少逗号。请检查 "config.py" 文件的第 56 行，并确保在 "key" 字典的最后一个元素后面添加逗号“ ,”
- 原代码
```Python
"key": {
    "enable": False,
    "_enable-desc": "是否开启请求key，开启后只有请求头中包含key，且值一样时可以访问API",
    "ban": True,
    "value": "114514",
}
"whitelist_host": [
    "localhost",
    "0.0.0.0",
    "127.0.0.1",
],
```

- 代码书写不规范导致的BUG（修复）
```Python
"key": {
    "enable": False,
    "_enable-desc": "是否开启请求key，开启后只有请求头中包含key，且值一样时可以访问API",
    "ban": True,
    "value": "114514",
},
"whitelist_host": [
    "localhost",
    "0.0.0.0",
    "127.0.0.1",
],
```

**Comment by 2020sudo** [comment]
`#!/usr/bin/env python3

# ----------------------------------------
# - mode: python -
# - author: helloplhm-qwq -
# - name: main.py -
# - project: lx-music-api-server -
# - license: MIT -
# ----------------------------------------
# 这个文件是 "lx-music-api-server" 项目的一部分。
# 除非你知道你在做什么，否则请不要编辑。

# 导入Flask库
from flask import Flask, request

# 创建Flask应用程序
app = Flask("LXMusicTestAPI")

# 将默认的Flask日志重定向到自定义日志
import logging
from common import config
from common import log

# 设置Flask日志记录器
flask_logger = log.log('flask')
logging.getLogger('werkzeug').addHandler(log.flaskLogHelper(flask_logger))
logger = log.log("main")

# 导入通用工具
from common import utils
from common import lxsecurity
from apis import SongURL

require = utils.require

# 定义根路径的路由，返回一个JSON响应
@app.route('/')
def index():
    return utils.format_dict_json({"code": 0, "msg": "success", "data": None}), 200

# 定义一个接收路径参数的路由，处理不同的API请求
@app.route('/<method>/<source>/<songId>/<quality>')
async def handle(method, source, songId, quality):
    # 检查安全设置，包括请求密钥和lxm请求头
    if (config.read_config("security.key.enable") and request.host.split(':')[0] not in config.read_config('security.whitelist_host')):
        if (request.headers.get("X-Request-Key") != config.read_config("security.key.value")):
            if (config.read_config("security.key.ban")):
                config.ban_ip(request.remote_addr)
            return utils.format_dict_json({"code": 1, "msg": "key验证失败", "data": None}), 403
    if (config.read_config('security.check_lxm.enable') and request.host.split(':')[0] not in config.read_config('security.whitelist_host')):
        lxm = request.headers.get('lxm')
        if (not lxsecurity.checklxmheader(lxm, request.url)):
            if (config.read_config('security.lxm_ban.enable')):
                config.ban_ip(request.remote_addr)
            return utils.format_dict_json({"code": 1, "msg": "lxm请求头验证失败", "data": None}), 403
    
    # 根据不同的请求类型调用相应的函数
    if method == 'url':
        return utils.format_dict_json(await SongURL(source, songId, quality))
    else:
        return utils.format_dict_json({'code': 6, 'msg': '未知的请求类型: ' + method, 'data': None}), 400

# 处理服务器内部错误的路由，返回500错误
@app.errorhandler(500)
def _500(_):
    return utils.format_dict_json({'code': 4, 'msg': '内部服务器错误', 'data': None}), 500

# 处理未找到资源的路由，返回404错误
@app.errorhandler(404)
def _404(_):
    return utils.format_dict_json({'code': 6, 'msg': '未找到您所请求的资源', 'data': None}), 404

# 在每次请求前执行的函数，用于检查IP封禁和请求的来源
@app.before_request
def check():
    if (request.headers.get("X-Real-IP")):
        request.remote_addr = request.headers.get("X-Real-IP")
    if (config.check_ip_banned(request.remote_addr)):
        return utils.format_dict_json({"code": 1, "msg": "您的IP已被封禁", "data": None}), 403
    config.updateRequestTime(request.remote_addr)
    if (config.read_config("security.allowed_host.enable")):
        if request.remote_host.split(":")[0] not in config.read_config("security.allowed_host.list"):
            if config.read_config("security.allowed_host.blacklist.enable"):
                config.ban_ip(request.remote_addr, int(config.read_config("security.allowed_host.blacklist.length")))
            return utils.format_dict_json({'code': 6, 'msg': '未找到您所请求的资源', 'data': None}), 404

# 启动Flask应用程序
app.run(host=config.read_config('common.host'), port=config.read_config('common.port'))
`

**Comment by 2020sudo** [comment]
```Python

#!/usr/bin/env python3

# ----------------------------------------
# - mode: python -
# - author: helloplhm-qwq -
# - name: main.py -
# - project: lx-music-api-server -
# - license: MIT -
# ----------------------------------------
# 这个文件是 "lx-music-api-server" 项目的一部分。
# 除非你知道你在做什么，否则请不要编辑。

# 导入Flask库
from flask import Flask, request

# 创建Flask应用程序
app = Flask("LXMusicTestAPI")

# 将默认的Flask日志重定向到自定义日志
import logging
from common import config
from common import log

# 设置Flask日志记录器
flask_logger = log.log('flask')
logging.getLogger('werkzeug').addHandler(log.flaskLogHelper(flask_logger))
logger = log.log("main")

# 导入通用工具
from common import utils
from common import lxsecurity
from apis import SongURL

require = utils.require

# 定义根路径的路由，返回一个JSON响应
@app.route('/')
def index():
    return utils.format_dict_json({"code": 0, "msg": "success", "data": None}), 200

# 定义一个接收路径参数的路由，处理不同的API请求
@app.route('/<method>/<source>/<songId>/<quality>')
async def handle(method, source, songId, quality):
    # 检查安全设置，包括请求密钥和lxm请求头
    if (config.read_config("security.key.enable") and request.host.split(':')[0] not in config.read_config('security.whitelist_host')):
        if (request.headers.get("X-Request-Key") != config.read_config("security.key.value")):
            if (config.read_config("security.key.ban")):
                config.ban_ip(request.remote_addr)
            return utils.format_dict_json({"code": 1, "msg": "key验证失败", "data": None}), 403
    if (config.read_config('security.check_lxm.enable') and request.host.split(':')[0] not in config.read_config('security.whitelist_host')):
        lxm = request.headers.get('lxm')
        if (not lxsecurity.checklxmheader(lxm, request.url)):
            if (config.read_config('security.lxm_ban.enable')):
                config.ban_ip(request.remote_addr)
            return utils.format_dict_json({"code": 1, "msg": "lxm请求头验证失败", "data": None}), 403
    
    # 根据不同的请求类型调用相应的函数
    if method == 'url':
        return utils.format_dict_json(await SongURL(source, songId, quality))
    else:
        return utils.format_dict_json({'code': 6, 'msg': '未知的请求类型: ' + method, 'data': None}), 400

# 处理服务器内部错误的路由，返回500错误
@app.errorhandler(500)
def _500(_):
    return utils.format_dict_json({'code': 4, 'msg': '内部服务器错误', 'data': None}), 500

# 处理未找到资源的路由，返回404错误
@app.errorhandler(404)
def _404(_):
    return utils.format_dict_json({'code': 6, 'msg': '未找到您所请求的资源', 'data': None}), 404

# 在每次请求前执行的函数，用于检查IP封禁和请求的来源
@app.before_request
def check():
    if (request.headers.get("X-Real-IP")):
        request.remote_addr = request.headers.get("X-Real-IP")
    if (config.check_ip_banned(request.remote_addr)):
        return utils.format_dict_json({"code": 1, "msg": "您的IP已被封禁", "data": None}), 403
    config.updateRequestTime(request.remote_addr)
    if (config.read_config("security.allowed_host.enable")):
        if request.remote_host.split(":")[0] not in config.read_config("security.allowed_host.list"):
            if config.read_config("security.allowed_host.blacklist.enable"):
                config.ban_ip(request.remote_addr, int(config.read_config("security.allowed_host.blacklist.length")))
            return utils.format_dict_json({'code': 6, 'msg': '未找到您所请求的资源', 'data': None}), 404

# 启动Flask应用程序
app.run(host=config.read_config('common.host'), port=config.read_config('common.port'))

```

**Comment by LarchLiu** [comment]
This issue has been fixed in #1 and this repo has been moved to [lx-music-api-server-python](https://github.com/lxmusics/lx-music-api-server-python)

**Comment by helloplhm-qwq** [comment]
已修复
那会在去学校路上写的代码没跑过😅
